### ISSUE TITLE
Coverage is only picking up spec files

### ISSUE THREAD

**Issue by mwq27** [basti1302/angular-browserify#2]
I'm trying to use karma-coverage reporter in my app, but it isn't covering any of the source code.  Has anyone seen this problem?

**Comment by basti1302** [comment]
Honestly, I have no clue. I haven't used karma-coverage until now. I'll leave this open for a while, maybe someone else can help you. But I guess there are better places to get help than an issue in this repo (stackoverflow.com or maybe the karma-coverage repo).

**Comment by mwq27** [comment]
Alright I figured out how to get coverage working using istanbul outside of karma coverage.  Apparently karma-coverage just doesn't work with browserified code.
